stage 'compileAndUnit'

def gradle;

node {

        // get source code
        checkout scm

        gradle = load 'jenkins/gradle.groovy'

        // check that the whole project compiles
        //gradle 'clean compileJava'
        gradle.cleanAndCompile()

        // save source code so we don't need to get it every time and also avoids conflicts
        stash excludes: 'build/', includes: '**', name: 'source'

        // execute required tests for commit stage in parallel
        parallel (
             "unit tests" : {
                gradle.test()
             },
             "commit integration tests" : {
                gradle.test('integration-commit-test')
             }
           )

        // save coverage reports for being processed during code quality phase.
        stash includes: 'build/jacoco/*.exec', name: 'unitCodeCoverage'
        stash includes: 'integration-commit-test/build/jacoco/*.exec', name: 'commitIntegrationCodeCoverage'

        // publish JUnit results to Jenkins
        step([$class: 'JUnitResultArchiver', testResults: '**/build/test-results/*.xml'])
}

stage 'codeQuality'

node {

    parallel (
        'pmd' : {
            // static code analysis
            unstash 'source'

            gradle.codeQuality()
            step([$class: 'PmdPublisher', pattern: 'build/reports/pmd/*.xml'])
        },
        'jacoco': {
            // jacoco report rendering
            unstash 'source'
            unstash 'unitCodeCoverage'
            unstash 'commitIntegrationCodeCoverage'

            gradle.aggregateJaCoCoReports()
            publishHTML(target: [reportDir:'build/reports/jacoco/jacocoRootTestReport/html', reportFiles: 'index.html', reportName: 'Code Coverage'])
        }
      )
}

stage 'assemble-binaries'

def starwarsImage;

node {
    // unstash source code and assemble the application
    // with BUILD_NUMBER
    unstash 'source'
    withEnv(["SOURCE_BUILD_NUMBER=${env.BUILD_NUMBER}"]) {
        gradle.assembleApplication()
    }

    // find created war, read the manifest to take the version

    def tagVersion = 'latest'
    def warFiles = findFiles(glob: 'build/libs/*.war')

    if (warFiles.length == 1) {
        def man = readManifest file: "build/libs/${warFiles[0].name}"
        tagVersion = man.main['Implementation-Version'] != null ? man.main['Implementation-Version'] : 'latest'
    } else {
        echo "0 or More than one WAR file generated by build."
        currentBuild.result = "UNSTABLE"
    }

    // create docker image with version

    starwarsImage = docker.build "starwars/planets:${tagVersion}"

    // runs container tests to be sure that the image is correctly created and it works

}


stage name: 'publish-binaries', concurrency: 1

node {
    unstash 'source'
    withEnv(["SOURCE_BUILD_NUMBER=${env.BUILD_NUMBER}"]) {
        gradle.publishApplication()
    }
}

input message: "Deploy Application to Test ?"

setCheckpoint('Before Deploying to Test')

stage name: 'Deploy to Test', concurrency: 1
node {

    def configFile = readFile 'gradle/config.groovy'
    def parsedConfig = new ConfigSlurper('test').parse(configFile)

    // docker
    println parsedConfig.docker.registry
    echo "Star Wars Application Deployed to QA."
}

void setCheckpoint(String message) {
    try {
        checkpoint(message)
    } catch (NoSuchMethodError _) {
        echo 'Checkpoint feature available in CloudBees Jenkins Enterprise.'
    }
}

void gradle(String tasks, String switches = null) {
    String gradleCommand = "";
    gradleCommand += './gradlew '
    gradleCommand += tasks

    if(switches != null) {
        gradleCommand += ' '
        gradleCommand += switches
    }

    sh gradleCommand.toString()
}